// Frontend configuration. Values are populated by Vite from web/.env.local
// (generated by scripts/lib/sync-web-env.sh from the active backend mode
// file). Values are validated at module load so a misconfigured build
// fails fast rather than at the first API call.

type AppConfig = {
  apiBase: string;
};

function readRequired(key: string): string {
  const v = (import.meta.env as Record<string, string | undefined>)[key];
  if (!v || v.trim() === "") {
    throw new Error(`Missing required frontend config: ${key}`);
  }
  return v;
}

export const appConfig: AppConfig = {
  apiBase: readRequired("VITE_API_BASE"),
};
