#!/usr/bin/env bash
# Generate web/.env.local from the resolved env. We pick up every VITE_*
# variable currently in the environment (which load-env.sh has populated
# from config/<mode>.env, .env.local, and the process env) and write them
# to web/.env.local for Vite to consume.
#
# The generated file is gitignored.

set -euo pipefail

REPO_ROOT="${LIVEABOARD_REPO_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
out="${REPO_ROOT}/web/.env.local"

{
  echo "# Generated by scripts/lib/sync-web-env.sh — do not edit by hand."
  echo "# Source: config/${LIVEABOARD_MODE:-dev}.env (+ .env.local if dev/test)"
  while IFS= read -r line; do
    case "${line}" in
      VITE_*) echo "${line}" ;;
    esac
  done < <(env)
} > "${out}.tmp"
mv "${out}.tmp" "${out}"
